* Lexical Binding
#+begin_src emacs-lisp
  ;; -*- lexical-binding: t; -*-
#+end_src

* Package Management
Has been moved outside of the literate config file due to org-mode mismatching version.
Specifically, org-roam uses more recent org-mode, but I use old org-mode provided org-babel-load-file function first.
And I install org-roam package using straight.el and use-package, so their setup are moved outside along with org-roam's.

* UI
** Basic
#+begin_src emacs-lisp
  (let ((disable-mode-list '(scroll-bar-mode tool-bar-mode menu-bar-mode))
	(enable-mode-list '(global-display-line-numbers-mode)))
    (mapcar (lambda (mode-func)
	      (funcall mode-func -1))
	    disable-mode-list)
    (mapcar (lambda (mode-func)
	      (funcall mode-func 1))
	    enable-mode-list)
    (setq inhibit-startup-screen t)
    (setq inhibit-startup-message t)
    (toggle-frame-maximized))
#+end_src
** Theme
#+begin_src emacs-lisp
  (use-package modus-themes
    :config
    (modus-themes-toggle))
#+end_src

* Development
** Language
*** zig
#+begin_src emacs-lisp
  (use-package zig-mode)
#+end_src
*** nix-mode
#+begin_src emacs-lisp
  (use-package nix-mode)
#+end_src
*** rust-mode
#+begin_src emacs-lisp
  (use-package rust-mode)
#+end_src
** Version Control
*** magit
#+begin_src emacs-lisp
  (use-package magit)
#+end_src

* Knowledge Management
** Markdown
#+begin_src emacs-lisp
  (use-package markdown-mode)
#+end_src
** org-roam
Because of mismatching org-mode version, it has been moved outside of literate config file.

** gptel
It's a simple and useful LLMs client for Emacs supporting many LLMs local and remote.
#+begin_src emacs-lisp
  (use-package gptel
    :config
    (setq
     gptel-model "phi3"
     gptel-backend (gptel-make-ollama "Ollama"
  				    :host "localhost:11434"
  				    :stream t
  				    :models '("moondream" "phi3"))))
#+end_src

** go-translate
It's a translation tool.
#+begin_src emacs-lisp
  (use-package go-translate
    :config
    (setq gt-langs '(en zh))
    (setq gt-default-translator (gt-translator :engines (gt-google-engine))))
#+end_src
